version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
      
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - command: |
        cp .circleci/mock.env.json .env.json
        sudo npm install -g grunt sass
        grunt build
        git config credential.helper 'cache --timeout=120'
        git config user.email "ericnakagawa@gmail.com"
        git config user.name "CircleCI Bot"
        git add .
        git commit -m "Deploying theme build via CircleCI"
        git push -q https://${GITHUB_PERSONAL_TOKEN}@github.com/pytorch/pytorch-sphinx-theme.git master

workflows:
  version: 2
  commit-and-build:
      jobs:
        - build
